### ISSUE TITLE
./test.sh

### ISSUE THREAD

**Issue by metouitude** [yuzhimanhua/HIMECat#1]
![Screenshot from 2021-07-13 21-32-33](https://user-images.githubusercontent.com/29012045/125513841-bc3b9348-df37-4b0c-8b46-bf500344c9b1.png)
Hey! thanks for sharing
I want to add that before this error occured another one occured :
FileNotFoundError: [Errno 2] No such file or directory: 'github/out.txt'
I created manually out.txt at github folder! then i got the screen below
i downloaded the data and my env are up to date!

**Comment by yuzhimanhua** [comment]
Hi, thank you for your interest in our work.

In ```test.sh```, there are two steps: ```main.py``` and ```eval.py```.
```github/out.txt``` is the output of ```main.py``` (i.e., the prediction result of our model). With this file, ```eval.py``` can calculate the F1 scores. 

According to your description, an error occurred in ```main.py```. That is "module "keras.utils.generic_utils" has no attribute "populate_dict_with_module_objects"". I think that's a version problem. The following package versions work from my side:
```
gensim==3.8.1
Keras==2.0.8
nltk==3.5
numpy==1.19.5
scikit-learn==0.20.0
spherecluster==0.1.7
tensorflow-gpu==1.15.0
```

Thank you for pointing out this! We will update ```requirement.txt``` to add the versions. If further errors occur, please let me know.
