### ISSUE TITLE
How to compute the topic dis over words beta in the code

### ISSUE THREAD

**Issue by daidaiduoduo** [yuzhimanhua/HIMECat#3]
Hello~ 
Thanks for sharing the code.
I met difficulty in computing beta. Could you please show an example? Thank you.

**Comment by yuzhimanhua** [comment]
Hi,

Thank you very much for your interest in our project!

Are you referring to "**the topic distribution over words**" (i.e., _p(w|l)_) or "**beta**" (i.e., the number of synthesized documents per class)?

**Comment by daidaiduoduo** [comment]
@yuzhimanhua 
Hello~ I mean "the topic distribution over words", for I want to get the top-N words in each topic (class).

**Comment by yuzhimanhua** [comment]
Got it! You want to compute _p(w|l)_, where "_w_" is a word and "_l_" is a category/topic.

Actually, we do not directly model _p(w|l)_. Instead, we model _p(d|l)_ and _p(w|d)_, where "_d_" is a document. Here, _p(d|l)_ follows the vMF distribution, and _p(w|d)_ follows a softmax distribution.

To give an example, let's assume we've already learned topic embeddings and word embeddings. Given a topic _l_, we assume its embedding is [1, 0]. Based on the topic embedding, we sample a document embedding from _p(d|l)_ (a vMF distribution). Say the sampled document embedding is [0.99, 0.05]. Then, we check which word is close to this document in the embedding space. The closer the word is to [0.99, 0.05], the more likely it will appear in the document.

Going back to your question, how to calculate _p(w|l)_ using the learned topic embeddings and word embeddings?

- (**Exact way**): You need to calculate the expectation E_d[_p(w|l)_] = \int_d _p(w|d) * p(d|l)_ . I feel it could be hard to compute this in practice.
- (**Approximated way**): Just find the nearest word neighbors of each topic in the embedding space by calculating the inner product of word embedding and topic embedding. Then, you don't even need to run ```./test.sh```. After ```./prep_emb.sh```, you can directly use the embeddings in ```./${dataset}/embedding_sph```.

**Comment by daidaiduoduo** [comment]
Oh, I get it.
Thank you for your detailed answer! *^_^*
